language: go
go: 
  - 1.2
  
env:
  - NEO_VERSION="2.0.0"

before_script:
  - go get launchpad.net/gocheck
  
after_success:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - tail +2 typescov.out >> cov.out
  - goveralls -coverprofile=cov.out rgaztLT7pidhfXGLbQz3bMowiBeB1XJlS
  
before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - echo "org.neo4j.server.transaction.timeout=1" >> neo4j-community-$NEO_VERSION/conf/neo4j-server.properties
  - neo4j-community-$NEO_VERSION/bin/neo4j start

script:
  - go test ./types -covermode=count -coverprofile=typescov.out
  - go test -covermode=count -coverprofile=cov.out
  - go test -gocheck.b
