language: go
go: 
  - 1.2
  
env:
  - NEO_VERSION="2.0.0"
  - NEO_VERSION="2.0.1"

before_script:
  - go get launchpad.net/gocheck
  
after_success:
  
before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - echo "org.neo4j.server.transaction.timeout=1" >> neo4j-community-$NEO_VERSION/conf/neo4j-server.properties
  - git clone https://github.com/jexp/neo4j-in-memory-server
  - cd neo4j-in-memory-server
  - ./copy.sh ../neo4j-community-$NEO_VERSION 
  - cd ..
  - neo4j-community-$NEO_VERSION/bin/neo4j start

script:
  - cd types
  - go test -covermode=count -coverprofile=../typescov.out
  - cd ..
  - go test -covermode=count -coverprofile=cov.out
  - go test -gocheck.b -covermode=count -coverprofile=bench.out
  - tail -n +2 typescov.out >> bench.out
  - tail -n +2 cov.out >> bench.out
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls -coverprofile=bench.out rgaztLT7pidhfXGLbQz3bMowiBeB1XJlS
