language: go
go: 
  - 1.2
  
after_success:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls rgaztLT7pidhfXGLbQz3bMowiBeB1XJlS
  
before_install:
  - wget dist.neo4j.org/neo4j-community-2.0.0-RC1-unix.tar.gz
  - tar -xzf neo4j-community-2.0.0-RC1-unix.tar.gz
  - neo4j-community-2.0.0-RC1/bin/neo4j start
