language: go
go: 
  - 1.4
  
env:
  - NEO_VERSION="3.0.0-alpha.LATEST"

before_script:
  - go get gopkg.in/check.v1
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  
after_success:
  - tail -n +2 typescov.out >> bench.out
  - tail -n +2 cov.out >> bench.out
  - goveralls -coverprofile=bench.out 
  
before_install:
  - go get golang.org/x/tools/cover
  - wget http://alpha.neotechnology.com.s3-website-eu-west-1.amazonaws.com/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - neo4j-community-$NEO_VERSION/bin/neo4j start

install:
  - go get gopkg.in/cq.v1

script:
  - cd ../../../gopkg.in/cq.v1/
  - cd types
  - go test -covermode=count -coverprofile=../typescov.out
  - cd ..
  - go test -covermode=count -coverprofile=cov.out
  - go test -check.b -covermode=count -coverprofile=bench.out
