language: go
go: 
  - 1.2
  
before_install:
  - wget dist.neo4j.org/neo4j-community-2.0.0-RC1-unix.tar.gz
  - tar -xzf neo4j-community-2.0.0-RC1-unix.tar.gz
  - neo4j-community-2.0.0-RC1/bin/neo4j start
